name: vestium
channels:
  - defaults
dependencies:
  - python=3.11
  - selenium
  - pymongo
  - pip
  - openai
  - pip:
    - pinecone-client
    - python-dotenv
    - replicate
    - pinscrape