name: vestium
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - openai
  - pip:
    - pinecone-client==3.0.0
    - python-dotenv
    - replicate
    - flask
    - flask_cors