annotated-types==0.6.0
anyio==4.2.0
attrs==23.2.0
beautifulsoup4==4.11.1
certifi==2024.2.2
charset-normalizer==2.1.1
distro==1.9.0
h11==0.14.0
httpcore==1.0.2
httpx==0.26.0
idna==3.6
iniconfig==2.0.0
install==1.3.5
numpy==1.26.4
openai==1.12.0
opencv-python==4.9.0.80
packaging==23.2
pinecone-client==3.0.2
pinscrape==3.0.3
pluggy==1.4.0
pydantic==2.6.1
pydantic_core==2.16.2
pydotmap==0.1.3
pytest==7.2.0
python-dotenv==1.0.1
requests==2.28.1
sniffio==1.3.0
soupsieve==2.5
tqdm==4.64.0
typing_extensions==4.9.0
urllib3==1.26.18
